u = User.create(name: 'A', email: 'A', password: 'A')
Restaurant.create(name: "Tonkatsu Place", user: u)
Restaurant.create(name: "Hamburger Joint", user: u)
Restaurant.create(name: "Ramen Stand", user: u)
Restaurant.create(name: "Pizza Parlor", user: u)
Restaurant.create(name: "Chinese Food", user: u)

Cuisine.create(name: "Japanese")
Cuisine.create(name: "Korean")
Cuisine.create(name: "Chinese")
Cuisine.create(name: "Beer")
Cuisine.create(name: "American")
Cuisine.create(name: "Italian")
Cuisine.create(name: "Thai")
Cuisine.create(name: "French")
Cuisine.create(name: "Seafood")
Cuisine.create(name: "Russian")
Cuisine.create(name: "Turkish")
Cuisine.create(name: "Carribean")
