Restaurant.create(name: "Tonkatsu Place")
Restaurant.create(name: "Hamburger Joint")
Restaurant.create(name: "Ramen Stand")
Restaurant.create(name: "Pizza Parlor")
Restaurant.create(name: "Chinese Food")
